import { GRAY_SCALE } from '##theme/grayscale.constant';

export enum TBUTTON_SIZES {
  XSMALL = 'xsmall',
  SMALL = 'small',
  MEDIUM = 'medium',
  LARGE = 'large',
  XLARGE = 'xlarge',
  DETAILS_BOTTOM_BUTTON = 'details_bottom_button'
}

export const BUTTON_SIZES = {
  SMALL: 'small',
  MEDIUM: 'medium',
  LARGE: 'large'
};

export enum TBUTTON_FILL {
  TRANSPARENT = 'transparent',
  OUTLINE = 'outline',
  SOLID = 'solid',
  UNDERLINE = 'underline'
}

export const BUTTON_FILL = {
  TRANSPARENT: 'transparent',
  OUTLINE: 'outline',
  SOLID: 'solid',
  UNDERLINE: 'underline'
};

export enum TBUTTON_WIDTH {
  AUTO = 'auto',
  FULL = 'full'
}

export const BUTTON_WIDTH = {
  AUTO: 'auto',
  FULL: 'full'
};

export enum TBUTTON_COLOR_SCHEMES {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  INFO = 'INFO',
  POSITIVE = 'POSITIVE',
  WARNING = 'WARNING',
  NEGATIVE = 'NEGATIVE',
  CONTRAST = 'CONTRAST',
  CONTRAST_30 = 'CONTRAST_30',
  CONTRAST_HIGH = 'CONTRAST',
  CONTRAST_MEDIUM = 'CONTRAST',
  CONTRAST_LOW = 'CONTRAST',
  CONTRAST_MIN = 'CONTRAST',
  INVERTED = 'INVERTED'
}

export const BUTTON_SOLID_FILL_TEXT_COLORS = {
  PRIMARY: GRAY_SCALE.WHITE,
  SECONDARY: GRAY_SCALE.WHITE,
  INFO: GRAY_SCALE.WHITE,
  POSITIVE: GRAY_SCALE.WHITE,
  WARNING: GRAY_SCALE.BLACK,
  NEGATIVE: GRAY_SCALE.WHITE,
  CONTRAST: GRAY_SCALE.WHITE,
  CONTRAST_30: GRAY_SCALE.WHITE,
  CONTRAST_HIGH: GRAY_SCALE.WHITE,
  CONTRAST_MEDIUM: GRAY_SCALE.WHITE,
  CONTRAST_LOW: GRAY_SCALE.WHITE,
  CONTRAST_MIN: GRAY_SCALE.WHITE,
  INVERTED: GRAY_SCALE.GRAY_20
};

export const BUTTON_COLOR_SCHEMES = {
  PRIMARY: 'PRIMARY',
  SECONDARY: 'SECONDARY',
  INFO: 'INFO',
  POSITIVE: 'POSITIVE',
  WARNING: 'WARNING',
  NEGATIVE: 'NEGATIVE',
  CONTRAST: 'CONTRAST',
  CONTRAST_30: 'CONTRAST_30',
  CONTRAST_HIGH: 'CONTRAST',
  CONTRAST_MEDIUM: 'CONTRAST',
  CONTRAST_LOW: 'CONTRAST',
  CONTRAST_MIN: 'CONTRAST',
  INVERTED: 'INVERTED'
};
