export const BASE_SPACING = 16;

export const SMALL_SPACING = 5;
export const NORMAL_SPACING = 10;
export const MEDIUM_SPACING = 15;
export const LARGE_SPACING = 20;
export const XLARGE_SPACING = 30;
export const XX_LARGE_SPACING = 40;

export const BASE_PADDING = BASE_SPACING;

export const SMALL_PADDING = SMALL_SPACING;
export const NORMAL_PADDING = NORMAL_SPACING;
export const MEDIUM_PADDING = MEDIUM_SPACING;
export const LARGE_PADDING = LARGE_SPACING;
export const XLARGE_PADDING = XLARGE_SPACING;
export const XX_LARGE_PADDING = XX_LARGE_SPACING;

export const BASE_MARGIN = BASE_SPACING;

export const SMALL_MARGIN = SMALL_SPACING;
export const NORMAL_MARGIN = NORMAL_SPACING;
export const MEDIUM_MARGIN = MEDIUM_SPACING;
export const LARGE_MARGIN = LARGE_SPACING;
export const XLARGE_MARGIN = XLARGE_SPACING;
export const XXLARGE_MARGIN = XX_LARGE_SPACING;

export const XSMALL_BORDER_RADIUS = 1;
export const SMALL_BORDER_RADIUS = 2;
export const MEDIUM_BORDER_RADIUS = 4;
export const X_MEDIUM_BORDER_RADIUS = 8;
export const LARGE_BORDER_RADIUS = 10;
export const X_LARGE_BORDER_RADIUS = 20;

export const DISPLAY_CELL_IMAGE_SIZE = 75;
export const NAV_CELL_IMAGE_SIZE = 60;
export const ITEM_DETAILS_IMAGE_SIZE = 300;

export const ICON_ROW_HEIGHT = 25;
export const ICON_ROW_ICON_WIDTH = 30;

export const ICON_SIZE = {
  SMALL: 16,
  NORMAL: 18,
  MEDIUM: 20,
  LARGE: 32
};

export const TAB_MENU_HEIGHT: number = 70;
export const TAB_MENU_ACTION_BUTTON_DIAMETER: number = 67;
export const TAB_MENU_ACTION_ITEM_BORDER_WIDTH: number = 9;
export const TAB_MENU_ACTION_ITEM_PROTRUSION: number =
  TAB_MENU_ACTION_BUTTON_DIAMETER + 2 * TAB_MENU_ACTION_ITEM_BORDER_WIDTH - TAB_MENU_HEIGHT;

export const IPHONE_BOTTOM_INSET_HEIGHT = 34;
export const CONTENT_CONTAINER_PADDING_BOTTOM =
  IPHONE_BOTTOM_INSET_HEIGHT + TAB_MENU_HEIGHT + TAB_MENU_ACTION_ITEM_PROTRUSION + LARGE_SPACING;

export const REFINE_SEARCH_MODAL_SECTION_LIST_PADDING_BOTTOM: number = XX_LARGE_PADDING;

export const KEYBOARD_VERTICAL_OFFSET = IPHONE_BOTTOM_INSET_HEIGHT + XX_LARGE_PADDING;
