export const DEFAULT_ICON_SIZE = 22;

export interface GLYPH {
  family: string;
  name: string;
}
export interface ICON_GLYPH {
  [k: string]: GLYPH;
}
export const ICON_GLYPH_MAP: ICON_GLYPH = {
  CHEVRON_LEFT: { family: 'netzer', name: 'netzer-chevron-left' },

  ADD_SHOPPING_CART: { family: 'netzer', name: 'netzer-add-to-cart' },
  ADD_SHOPPING_LIST: { family: 'netzer', name: 'netzer-list-add' },
  ADD_CONTACT_INFO: { family: 'netzer', name: 'netzer-add-contact-info' },
  ADD_TIMESLOT: { family: 'netzer', name: 'netzer-select-timeslot' },
  AGE_RESTRICTED: { family: 'netzer', name: 'netzer-identification' },
  BARCODE_SCAN: { family: 'netzer', name: 'netzer-barcode-scan' },
  CALENDAR: { family: 'netzer', name: 'netzer-calendar' },
  CHEVRON_RIGHT: { family: 'netzer', name: 'netzer-chevron-right' },
  CLEAR: { family: 'netzer', name: 'netzer-close' },
  CLIP: { family: 'netzer', name: 'netzer-cut' },
  COUPON_CLIP: { family: 'netzer', name: 'netzer-coupon' },
  CLOCK: { family: 'fontawesome', name: 'clock' },
  CLOSE: { family: 'netzer', name: 'netzer-close-1' },
  EDIT_PENCIL: { family: 'netzer', name: 'netzer-edit-pencil' },
  FORBIDDEN: { family: 'netzer', name: 'netzer-forbidden' },
  MENU: { family: 'netzer', name: 'netzer-hamburger' },
  MISSING_PAGE: { family: 'netzer', name: 'netzer-missing-page' },
  PIG_BANK: { family: 'netzer', name: 'netzer-piggybank' },
  LOCATION: { family: 'netzer', name: 'netzer-location-pin' },
  LOYALTY_POINTS_CARD: { family: 'netzer', name: 'netzer-loyalty-points-card' },
  REWARDS: { family: 'netzer', name: 'netzer-rewards' },
  SEARCH: { family: 'netzer', name: 'netzer-search' },
  SHOP: { family: 'netzer', name: 'netzer-shop' },
  SMARTPHONE: { family: 'netzer', name: 'netzer-smartphone' },
  SNAP: { family: 'netzer', name: 'netzer-snap' },
  SNAP_EBT: { family: 'netzer', name: 'netzer-snap-ebt' },
  SORT: { family: 'netzer', name: 'netzer-sort' },
  STAR: { family: 'netzer', name: 'netzer-star' },
  PLUS: { family: 'netzer', name: 'netzer-plus' },
  MINUS: { family: 'fontawesome', name: 'minus' },
  LOGIN: { family: 'netzer', name: 'netzer-avatar' },
  YOUTUBE: { family: 'netzer', name: 'netzer-youtube' },
  CHECK: { family: 'netzer', name: 'netzer-checkmark' },
  CHECK_CIRCLE: { family: 'fontawesomeicon', name: 'check-circle' },
  REFINE: { family: 'netzer', name: 'netzer-filter' },
  VIEW: { family: 'netzer', name: 'netzer-view' },
  DIRECTIONS: { family: 'netzer', name: 'netzer-directions' },
  STORE_FLYERS: { family: 'netzer', name: 'netzer-store-flyer' },
  STOREFRONT: { family: 'netzer', name: 'netzer-store' },
  CALL: { family: 'netzer', name: 'netzer-call' },
  TRIANGLE_DOWN: { family: 'netzer', name: 'netzer-triangle-down' },
  TIMER: { family: 'netzer', name: 'netzer-inprogress' },
  IMAGE: { family: 'materialcommunityicons', name: 'image' },
  REFRESH: { family: 'fontawesomeicon', name: 'refresh' },
  EYE: { family: 'fontawesomeicon', name: 'eye' },
  EYE_SLASH: { family: 'fontawesomeicon', name: 'eye-slash' },
  OUTLINED_CIRCLE: { family: 'fontawesomeicon', name: 'circle-thin' },
  CIRCLE: { family: 'netzer', name: 'netzer-close-round' },
  MAP_MARKER: { family: 'fontawesome', name: 'map-marker' },
  EXTERNAL_LINK: { family: 'fontawesome', name: 'external-link-alt' },
  LOCATE: { family: 'materialicons', name: 'my-location' },
  TRASH_CAN: { family: 'netzer', name: 'netzer-trash' },
  OK_CIRCLED: { family: 'netzer', name: 'netzer-ok-circled' },
  CANCEL_CIRCLED: { family: 'netzer', name: 'netzer-cancel-circled' },
  CHEVRON_UP: { family: 'netzer', name: 'netzer-chevron-up' },
  CHEVRON_THIN_UP: { family: 'netzer', name: 'netzer-thin-chevron-up' },
  SPINNER: { family: 'fontawesomeicon', name: 'spinner' },
  ALERT_CIRCLE: { family: 'netzer', name: 'netzer-alert-circle' },
  EXCLAMATION_CIRCLE: { family: 'fontawesome', name: 'exclamation-circle' },
  DELIVERY_TRUCK: { family: 'netzer', name: 'netzer-delivery-truck' },
  SHOP_BAG: { family: 'netzer', name: 'netzer-shop-bag' },
  NAVIGATION: { family: 'netzer', name: 'netzer-navigation' },
  ARROW_UP_LEFT: { family: 'netzer', name: 'netzer-arrow-up-left' },
  CC_VISA: { family: 'fontawesomeicon', name: 'cc-visa' },
  CC_DINERS: { family: 'fontawesomeicon', name: 'cc-diners-club' },
  CC_MASTERCARD: { family: 'fontawesomeicon', name: 'cc-mastercard' },
  CC_JCB: { family: 'fontawesomeicon', name: 'cc-jcb' },
  CC_AMEX: { family: 'fontawesomeicon', name: 'cc-amex' },
  CC_DISCOVER: { family: 'fontawesomeicon', name: 'cc-discover' },
  CART_PICKUP: { family: 'netzer', name: 'netzer-pickup' },
  INFO: { family: 'materialcommunityicons', name: 'information' },
  RADIO_BOX_UNSELECTED: { family: 'materialcommunityicons', name: 'radiobox-blank' },
  RADIO_BOX_SELECTED: { family: 'materialcommunityicons', name: 'radiobox-marked' },
  PARITY: { family: 'fontawesomeicon', name: 'table' },
  ADD_PAYMENT_CARD: { family: 'netzer', name: 'netzer-add-payment-card' },
  NOTES: { family: 'netzer', name: 'netzer-notes' },
  ADD_TO_LIST: { family: 'netzer', name: 'netzer-add-to-list' },
  SHARE_IOS: { family: 'netzer', name: 'netzer-share-ios' },
  SHARE_ANDROID: { family: 'netzer', name: 'netzer-share-android' },
  DEAL_GROUP: { family: 'netzer', name: 'netzer-deal-group' },

  // ionicons
  HOME: { family: 'ionicons', name: 'home-outline' },
  PRODUCTS: { family: 'ionicons', name: 'color-filter-outline' },
  CART: { family: 'ionicons', name: 'cart' },
  PROFILE: { family: 'ionicons', name: 'person-outline' },
  ELLIPSIS_H: { family: 'ionicons', name: 'ios-ellipsis-horizontal' },
  TRASH_OUTLINE: { family: 'ionicons', name: 'trash-outline' },
  CART_OUTLINE: { family: 'ionicons', name: 'cart-outline' },
  REMOVE_OUTLINE: { family: 'ionicons', name: 'remove-outline' },
  ADD_OUTLINE: { family: 'ionicons', name: 'add-outline' },
  VERTICAL_ELLIPSIS: { family: 'ionicons', name: 'ios-ellipsis-vertical' },
  CHECKBOX_BLANK_OUTLINE: { family: 'ionicons', name: 'square-outline' },
  CHECKBOX_CHECKED_OUTLINE: { family: 'ionicons', name: 'checkbox-outline' },
  SAVE_OUTLINE: { family: 'ionicons', name: 'save-outline' },
  CLOSE_OUTLINE: { family: 'ionicons', name: 'close-outline' },
  CLOSE_SESSION: { family: 'ionicons', name: 'ios-exit-outline' },
  PRICETAGS_SESSION: { family: 'ionicons', name: 'pricetags-outline' }
};

export const DEFAULT_WL_PAYMENT_CARD_ICON = ICON_GLYPH_MAP.CC_VISA;

export const WLICON_GLYPH_MAP_FALLBACK = ICON_GLYPH_MAP.CLOSE;
